version: '3.8'

services:
  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=movie_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456789
    volumes:
      - mysql-data:/var/lib/mysql
      - ./movie_app.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
  web:
    image: movie-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-net
    depends_on:
      - mysql
volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge
