application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '3600000'
      refresh-token:
        expiration: '86400000'
  service:
    user:
      userPerPage: '5'
    movie:
      moviePerPage: '5'
    room:
      roomPerPage: '5'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  datasource:
    password: 'password'
    username: root
    url: jdbc:mysql://localhost:3306/movie_app
  cloudinary:
    api:
      secret: u3aoCSJzt31lcqOJBsgykwTq81o
      key: '593637822396816'
    name: di6h4mtfa
server:
  port : 8080
