on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Debug Network
        run: |
          echo "Pinging server..."
          ping -c 4 ${{ secrets.SSH_HOST }} || echo "Ping failed"
      
          echo "Checking if SSH port 22 is open..."
          nc -zv ${{ secrets.SSH_HOST }} 22 || echo "Port 22 closed or unreachable"


      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       echo "✅ SSH Connection Successful!"
      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'
      # - name: Unit Tests
      #   run: mvn -B test --file pom.xml

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      # - name: Build the application
      #   run: |
      #     mvn clean
      #     mvn -B package --file pom.xml

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     dockerfile: Dockerfile
      #     push: false
      #     tags: ${{ secrets.DOCKER_USERNAME }}/movie-backend
      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     dockerfile: Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/movie-backend
